[package]
name = "michael-ascent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascent = { path = "../ascent" }
rand = "0.8.5"
rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"