[package]
name = "ascent"
version = "0.1.0"
edition = "2021"
authors = ["Arash Sahebolamri"]
description = "Logic programming in Rust"
keywords = ["logic-programming", "program-analysis", "Datalog", "procedural-macro"]
categories = ["compilers"]
homepage = "https://s-arash.github.io/ascent/"
repository = "https://github.com/s-arash/ascent"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ascent_macro = {version = "0.1", path = "../ascent_macro"}
ascent_base = {version = "0.1", path = "../ascent_base"}
rustc-hash = "1.1"
nohash-hasher = "0.2.0"
mimalloc = { version = "0.1.24", default-features = false }
hashbrown = "0.11.2"