name: Rust

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo --version
    - name: Run tests
      run: cargo test test
    - name: Run macro tests
      working-directory: ./infer_macro
      run: cargo test test   
    - name: Run Benchmarks
      working-directory: .
      run: cargo bench bench_tc -- --nocapture
