name: Rust

on:
  push:
    branches: [ master, ci, lattices ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo --version
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          override: true
          toolchain: 1.59
    
    - run: cargo --version

    - name: Run ascent_tests tests
      working-directory: ./ascent_tests
      run: cargo test

    - name: Run ./ascent tests
      working-directory: ./ascent
      run: cargo test
    
    - name: Run ascent_base tests
      working-directory: ./ascent_base
      run: cargo test
    
    - name: Run Benchmarks
      working-directory: ./ascent_tests
      run: cargo bench bench_tc -- --nocapture
    
      # macro tests should be last, because they produce scratchpad.rs, which my not compile
    - name: Run macro tests
      working-directory: ./ascent_macro
      run: cargo test test  
