name: Rust

on:
  push:
    branches: [ master, ci, lattices ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo --version
    - name: Run tests
      working-directory: ./infer_tests
      run: cargo test test
    - name: Run infer_base tests
      working-directory: ./infer_base
      run: cargo test
    - name: Run Benchmarks
      working-directory: ./infer_tests
      run: cargo bench bench_tc -- --nocapture
      # macro tests should be last, because they produce scratchpad.rs, which my not compile
    - name: Run macro tests
      working-directory: ./infer_macro
      run: cargo test test  
